// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASPDYerYm3Js4hnoDtkZy8Rrq-MwGUA-8',
    appId: '1:723220012407:web:906b4cd869db4a12779572',
    messagingSenderId: '723220012407',
    projectId: 'campusfind-pk',
    authDomain: 'campusfind-pk.firebaseapp.com',
    storageBucket: 'campusfind-pk.firebasestorage.app',
    measurementId: 'G-DT1T0T0B49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmwgeV0q0MYDAp-mMywAikm_9AdgoyLaE',
    appId: '1:723220012407:android:4b0ebe0531cd40cf779572',
    messagingSenderId: '723220012407',
    projectId: 'campusfind-pk',
    storageBucket: 'campusfind-pk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd2XaoN36WcSMh6ToiCo9Ihmw-TTQHEVA',
    appId: '1:723220012407:ios:c8a5abef813ed0f1779572',
    messagingSenderId: '723220012407',
    projectId: 'campusfind-pk',
    storageBucket: 'campusfind-pk.firebasestorage.app',
    iosBundleId: 'com.example.campusfindPk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd2XaoN36WcSMh6ToiCo9Ihmw-TTQHEVA',
    appId: '1:723220012407:ios:c8a5abef813ed0f1779572',
    messagingSenderId: '723220012407',
    projectId: 'campusfind-pk',
    storageBucket: 'campusfind-pk.firebasestorage.app',
    iosBundleId: 'com.example.campusfindPk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASPDYerYm3Js4hnoDtkZy8Rrq-MwGUA-8',
    appId: '1:723220012407:web:187b4aa458e0f264779572',
    messagingSenderId: '723220012407',
    projectId: 'campusfind-pk',
    authDomain: 'campusfind-pk.firebaseapp.com',
    storageBucket: 'campusfind-pk.firebasestorage.app',
    measurementId: 'G-M420B1BKMB',
  );
}
